vinosite/sharekernel/urls.py
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 07 13:28:02 2015

@author: sophie.martin
"""

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^compare/(?P<vinoA_id>([0-9]|N)+)/(?P<vinoB_id>([0-9]|N)+)/$', views.compareresult, name='compareresult'),
    url(r'^controltostate/(?P<result_id>([0-9]|N)+)/$', views.controltostate, name='controltostate'),
    url(r'^makeEvolutionViable/(?P<result_id>([0-9]|N)+)/$', views.makeEvolutionViable, name='makeEvolutionViable'),
    url(r'^problem/new/$', views.newproblem, name='newproblem'),
    url(r'^problem/(?P<viabilityproblem_id>([0-9]|N)+)/edit$', views.newproblem, name='editviabilityproblem'),
    url(r'^problem/(?P<viabilityproblem_id>([0-9]|N)+)/$', views.visitviabilityproblem, name='visitviabilityproblem'),
    url(r'^problem/(?P<viabilityproblem_id>([0-9]|N)+)/parameters/new/$', views.newparameters, name='newparameters'),
    url(r'^results/$', views.results_tree, name='results_tree'),
    url(r'^visitviabilityproblems/$', views.visitviabilityproblems, name='visitviabilityproblems'),
    url(r'^result/(?P<result_id>([0-9]|N)+)/edit$', views.editresult, name='editresult'),
    url(r'^result/(?P<result_id>([0-9]|N)+)/$', views.visitresult, name='visitresult'),
    url(r'^software/(?P<software_id>([0-9]|N)+)/$', views.visitsoftware, name='visitsoftware'),
    url(r'^software/new/$', views.newsoftware, name='newsoftware'),
    url(r'^upload/p=(?P<parameters_id>([0-9]|N)+)/a=(?P<software_id>([0-9]|N)+)/$', views.kerneluploadpage, name='kerneluploadpage'),
    # Upload feature without parameters selected disabled
    #url(r'^upload/$', views.kerneluploadpage, name='kerneluploadpage'),
    url(r'kerneluploadfile/', views.kerneluploadfile, name = 'kerneluploadfile' ),
    url(r'^ViNOComparison2D/(?P<vinoA_id>([0-9]|N)+)/(?P<vinoB_id>([0-9]|N)+)/(?P<ppa>([0-9]|N)+)/$', views.ViNOComparison2D, name='ViNOComparison2D'),
    url(r'^diff/(?P<vinoA_id>([0-9]|N)+)/(?P<vinoB_id>([0-9]|N)+)/(?P<ppa>([0-9]|N)+)/$', views.saveVinoDifference, name='saveVinoDifference'),
    url(r'^stateset/(?P<stateset_id>([0-9]|N)+)/$', views.viewStateSet, name='viewStateSet'),
    url(r'^ViNOView3D/(?P<result_id>([0-9]|N)+)/(?P<ppa>([0-9]|N)+)/$', views.ViNOView3D, name='ViNOView3D'),
    url(r'^ViNOView2D/(?P<result_id>([0-9]|N)+)/(?P<ppa>([0-9]|N)+)/$', views.ViNOView2D, name='ViNOView2D'),
    url(r'^ViNODistanceView/(?P<result_id>([0-9]|N)+)/(?P<ppa>([0-9]|NN)+)/(?P<permutnumber>([0-9]|NNN)+)/(?P<withdefdom>([0-9]|N)+)/$', views.ViNODistanceView, name='ViNODistanceView'),
    url(r'^ViNOHistogramDistance/(?P<result_id>([0-9]|N)+)/(?P<ppa>([0-9]|N)+)/(?P<hist_maxvalue>([0-9]|N)+)/$', views.ViNOHistogramDistance, name='ViNOHistogramDistance'),
    url(r'^bargrid2json/$', views.bargrid2json, name='bargrid2json'),
    url(r'^bargrid2jsonNew/(?P<result_id>([0-9]|N)+)/$', views.bargrid2jsonNew, name='bargrid2jsonNew'),
    url(r'^bargrid2json2/(?P<hist_maxvalue>([0-9]|N)+)/$', views.bargrid2json2, name='bargrid2json2'),
    url(r'^bargrid2json2New/(?P<result_id>([0-9]|N)+)/(?P<hist_maxvalue>([0-9]|N)+)/$', views.bargrid2json2New, name='bargrid2json2New'),
    url(r'^bargrid2json3/(?P<hist_maxvalue>([0-9]|N)+)/$', views.bargrid2json3, name='bargrid2json3'),
    url(r'^kerneluploaded/$', views.kerneluploaded, name='kerneluploaded'),
    url(r'^softwarelist/(?P<viabilityproblem_id>([0-9]|N)+)/(?P<parameters_id>([0-9]|N)+)/(?P<software_id>([0-9]|N)+)/(?P<resultformat_id>([0-9]|N)+)/$', views.softwarelist, name='softwarelist'),
    url(r'^algorithmlist/$', views.algorithmlist, name='algorithmlist'),
    url(r'^visualizeresult/(?P<result_id>([0-9]|N)+)/$', views.visualizeresult, name='visualizeresult'),
    url(r'^visualizeresulttrajectories/(?P<result_id>([0-9]|N)+)/$', views.visualizeresulttrajectories, name='visualizeresulttrajectories'),
]

vinosite/vinosite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('sharekernel.urls', namespace="sharekernel")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vinosite/sharekernel/models.py
from django.db import models
from django.conf import settings
from Equation import Expression
from django.utils import timezone

class BaseEntity(models.Model):
    title = models.CharField(max_length=500,default='')
    description = models.TextField(max_length=2000,default = '', blank=True)
    publication = models.TextField(max_length=1000,default ='', blank=True)
    website = models.URLField(default='', blank=True)
    submissiondate = models.DateTimeField('date published', default=timezone.now)
    submitter = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    author = models.CharField(max_length=500,default='', blank=True)
    contact = models.CharField(max_length=500,default='', blank=True)
    illustration = models.ImageField(upload_to='illustrations', default=None, blank=True)

    class Meta:
        abstract = True

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

class ViabilityProblem(BaseEntity):
    dynamicsdescription = models.CharField(max_length=500,default = '')
    admissiblecontroldescription = models.CharField(max_length=500,default = '')
    stateconstraintdescription = models.CharField(max_length=500,default = '')
    statedefinitiondomain = models.CharField(max_length=500,default = '', blank=True)
    admissiblecontrolbbox = models.CharField(max_length=500,default = '', blank=True)
    targetdescription = models.CharField(max_length=500,default = '')
    def dynamics(self):
      return [fulldyn.split("=")[1] for fulldyn in self.dynamicsdescription.split(",")]
    def constraints(self):
      return self.stateconstraintdescription.split(",")
    def definitiondomain(self):
      return self.statedefinitiondomain.split(",")
    def admissibles(self):
      return self.admissiblecontroldescription.split(",")
    def stateabbreviation(self):
      return [v.shortname for v in self.statevariables.all()]
    def statename(self):
      return [v.name for v in self.statevariables.all()]
    def controlabbreviation(self):
      return [v.shortname for v in self.controlvariables.all()]
    def controlname(self):
      return [v.name for v in self.controlvariables.all()]
    def stateconstraintparameterabbreviation(self):
      return [v.shortname for v in self.stateconstraintparameters.all()]


    def __str__(self):
        return str(self.pk) + " " + self.title

class Variable(models.Model):
    shortname = models.CharField(max_length=500)
    name = models.CharField(max_length=500,default ='', blank=True)
    unit = models.CharField(max_length=500,default ='', blank=True)
    class Meta:
        abstract = True
    def __repr__(self):
        return '["{}","{}","{}"]'.format(self.shortname, self.name, self.unit)
    def testrepr(self):
        return '["{}","{}","{}"]'.format(shortname, name, unit)
    def __str__(self):
        name = ""
        if len(self.name) > 1:
            name = " (" + self.name+")"
        return str(self.shortname) + name

class StateVariable(Variable):
    viabilityproblem = models.ForeignKey(ViabilityProblem, related_name='statevariables', on_delete=models.CASCADE)

class ControlVariable(Variable):
    viabilityproblem = models.ForeignKey(ViabilityProblem, related_name='controlvariables', on_delete=models.CASCADE)

class DynamicsParameter(Variable):
    viabilityproblem = models.ForeignKey(ViabilityProblem, related_name='dynamicsparameters', on_delete=models.CASCADE)

class StateConstraintParameter(Variable):
    viabilityproblem = models.ForeignKey(ViabilityProblem, related_name='stateconstraintparameters', on_delete=models.CASCADE)

class TargetParameter(Variable):
    viabilityproblem = models.ForeignKey(ViabilityProblem, related_name='targetparameters', on_delete=models.CASCADE)

class Software(BaseEntity):
    version = models.CharField(max_length=20,default='', blank=True)
    parameters = models.CharField(max_length=500,default = '', blank=True)
    def __str__(self):
        return str(self.pk) + " " + self.title + " " + self.version

class Parameters(BaseEntity):
    viabilityproblem = models.ForeignKey(ViabilityProblem)
    dynamicsparametervalues = models.CharField(max_length=200,default='', blank=True)
    stateconstraintparametervalues = models.CharField(max_length=200,default='', blank=True)
    targetparametervalues = models.CharField(max_length=200,default='', blank=True)
    def speed(self):
        eqdyns = []
        desstateandcontrol = []
        desdyn = self.viabilityproblem.dynamics()
        j=0
        for thing in self.viabilityproblem.dynamicsparameters.all():
             for i in range(len(desdyn)):
                  desdyn[i] = desdyn[i].replace(thing.shortname,self.dynamicsparametervalues.split(",")[j])
             j = j+1
        params= self.viabilityproblem.stateabbreviation()+self.viabilityproblem.controlabbreviation()

        for expr in desdyn :
            eqdyns.append(Expression(expr,params))
        return eqdyns
    def __str__(self):
        return str(self.pk) + " " + self.dynamicsparametervalues

    def admissibles(self):
        eqadms = []
        desstateandcontrol = []
        desadm = self.viabilityproblem.admissibles()
        j=0
        for thing in self.viabilityproblem.dynamicsparameters.all():
             for i in range(len(desadm)):
                  desadm[i] = desadm[i].replace(thing.shortname,self.dynamicsparametervalues.split(",")[j])
             j = j+1
        params= self.viabilityproblem.stateabbreviation()+self.viabilityproblem.controlabbreviation()

        for expr in desadm :
            eqadms.append(Expression(expr,params))
        return eqadms

    def constraints(self):
        eqcons = []
        desstateandcontrol = []
        descon = self.viabilityproblem.constraints()
        j=0
#        for thing in self.viabilityproblem.stateconstraintparameters.split(","):
        for thing in self.viabilityproblem.stateconstraintparameterabbreviation():
             for i in range(len(descon)):
                  descon[i] = descon[i].replace(thing,self.stateconstraintparametervalues.split(",")[j])
             j = j+1
        params= self.viabilityproblem.stateabbreviation()

        for expr in descon :
            eqcons.append(Expression(expr,params))
        return eqcons

    def definitiondomain(self):
        eqcons = []
        desstateandcontrol = []
        descon = self.viabilityproblem.definitiondomain()
        j=0
#        for thing in self.viabilityproblem.stateconstraintparameters.split(","):
        for thing in self.viabilityproblem.stateconstraintparameterabbreviation():
             for i in range(len(descon)):
                  descon[i] = descon[i].replace(thing,self.stateconstraintparametervalues.split(",")[j])
             j = j+1
        params= self.viabilityproblem.stateabbreviation()

        for expr in descon :
            eqcons.append(Expression(expr,params))
        return eqcons


    def leftandrighthandconstraints(self):
        eqcons = []
        desstateandcontrol = []
        descon = self.viabilityproblem.constraints()
        j=0
        for thing in self.viabilityproblem.stateconstraintparameterabbreviation():
             for i in range(len(descon)):
                  descon[i] = descon[i].replace(thing,self.stateconstraintparametervalues.split(",")[j])
             j = j+1
        params= self.viabilityproblem.stateabbreviation()

        for i in range(len(descon)):
             desconsplitted = descon[i].split("<=");
             if (len(desconsplitted)==2):
                 eqcons.append([Expression(desconsplitted[0],params),Expression(desconsplitted[1],params)])
             else :
                 desconsplitted = descon[i].split(">=");
                 if (len(desconsplitted)==2):
                     eqcons.append([Expression(desconsplitted[1],params),Expression(desconsplitted[0],params)])
        return eqcons

class ResultFormat(BaseEntity):
    parameterlist = models.CharField(max_length=500,default = '', blank=True)

    def __str__(self):
        return self.title

    def toDict(self):
        '''
        Return a representation of the format as a dictionnary.
        '''
        return {"pk":self.pk, "format":self.title, "description":self.description, "parameters":self.parameterlist.split(";")}

class Results(BaseEntity):
    parameters = models.ForeignKey(Parameters, null = True)
    software = models.ForeignKey(Software, null = True)
    resultformat = models.ForeignKey(ResultFormat, null=True)
    explorationdomain = models.CharField(max_length=500,default = '', blank=True)
    softwareparametervalues = models.CharField(max_length=500,default = '', blank=True)
    formatparametervalues = models.CharField(max_length=500,default = '', blank=True)
    datafile = models.FileField(upload_to='results/%Y/%m/%d')
    def __str__(self):
        return str(self.pk) + " " + str(self.submissiondate.strftime("%Y%m%d-%H%M"))+ " " + self.title

class StateSet(BaseEntity):
    '''
    Representation of a set of system states, independent of any dynamics or viability problem.
    This intends to be used for:
     - storing the result of an operation between two "Results" (for example a difference)
     - describing a complex constraint set of viability problem
    '''
    resultformat = models.ForeignKey(ResultFormat, null=True)
    datafile = models.FileField(upload_to='statesets/%Y/%m/%d')
    parents = models.ManyToManyField(Results, default=None)

vinosite/sharekernel/forms.py
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 11 13:49:04 2015

@author: sophie.martin
"""

from django import forms
from models import ViabilityProblem, Results, Parameters, Software

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label='Select a file',
        help_text='max. 42 megabytes'
    )

class ParametersSelect(forms.Select):
    def __init__(self, *args, **kwargs):
        super(ParametersSelect, self).__init__(*args, **kwargs)
        
    def render_option(self, selected_choices, option_value, option_label):
        selected_html = (option_value in selected_choices) and u' selected="selected"' or ''
        return u'<option value="%s"%s>%s</option>' % (option_value, selected_html, option_label)


class ResultForm(forms.ModelForm):
    class Meta:
        model=Results
        fields=('title','softwareparametervalues','formatparametervalues', 'parameters')
        # FIXME parameters doesn't have the initial value
        widgets = { 'parameters':ParametersSelect()}

class TrajForm(forms.Form):
    controlInput = forms.CharField(label = '(time,control value)',initial = 'essai')
    
class ViabilityProblemForm(forms.ModelForm):
    class Meta:
        model = ViabilityProblem
        exclude = ['category']
        
class ParametersForm(forms.ModelForm):
    class Meta:
        model = Parameters
        exclude = ['']
        widgets = {'viabilityproblem': forms.HiddenInput}

class SoftwareForm(forms.ModelForm):
    class Meta:
        model = Software
        exclude = ['']
        
class MetadataFromListForm(forms.Form):
    def __init__(self, metadata, *args, **kwargs):
        super(forms.Form, self).__init__(*args, **kwargs)
        # now we add each metadata individually
        for metadata in metadata:
             self.fields[metadata] = forms.CharField(label=metadata)

vinosite/sharekernel/templates/sharekernel/home.html
{% extends "base.html" %}
{% load staticfiles %}
  {% block head %}
<style>
a.btn{
    color:#800000;
}
</style>
{% endblock %}
{% block body %}

<div class="container">
    <div class="jumbotron">
<h2><font color="#800000">ViNO</font> : <font color="#800000">Vi</font>able <font color="#800000">N</font>umerical <font color="#800000">O</font>bject repository</h2>
<p>        Viability problems arise in several scientific fields (robotics, economics, environmental sciences). Once the set of constraints to be satisfied is specified
 and the dynamics described, the viability problem is the study of the compatibility between these constraints and these dynamics; 
Control strategies governing viable evolutions if any can then be deduced.<p>
<p> Analytical solutions to sustainability problems are very rare. 
Approximations can then be calculated, we call them <font color="#800000">Vi</font>able <font color="#800000">N</font>umerical <font color="#800000">O</font>bjects.<p>
 </div>
 <div class="row">
  <div class="col-sm-6"><a href="{% url 'sharekernel:visitviabilityproblems' %}"><img class="img-responsive"  src="{% static 'sharekernel/images/explore.png' %}" /></a></div>
  <div class="col-sm-6"><p><a href="{% url 'sharekernel:visitviabilityproblems' %}" class="btn btn-default" role="button">Click here </a> to visit ViNO repository and experiment on ViNOs thanks to the provided tools :<p> 
<ul>
                <li>	ViNO visualisation including the computation of the distance to the boundary</li>
                <li>	ViNO comparison </li>
                <li>	ViNO-based viable evolution design </li>

</ul></div>
</div>
 <hr>
 <div class="row">
  <div class="col-sm-6"><a href="{% url 'sharekernel:results_tree' %}"><img class="img-responsive"  src="{% static 'sharekernel/images/upload.png' %}" /></a></div>
  <div class="col-sm-6"><p><a href="{% url 'sharekernel:results_tree' %}" class="btn btn-default" role="button">Click here </a> to upload your ViNO, describe new problems addressed and 
benefit from the platform services to :<p> 
<ul>
                <li>	visualise your ViNO</li>
                <li>	compare your ViNO with already deposited ones</li>
                <li>	test your software performance </li>

</ul></div>
</div>

    </div>
<hr>
    <div id="row">
<!--        <div class="col-sm-8 col-sm-offset-2">
            <a href="{% url 'sharekernel:results_tree' %}">Explore</a> and describe new problems addressed, upload associated kernels and benefit from the platform services : 
            <ul>
                <li>	visualisation including the computation of the distance to the boundary</li>
                <li>	comparison with kernels obtained by other softwares (in progress) </li>
                <li>	viable evolution design (in progress) </li>
                <li>	automated test of your results (to do)</li> 
                <li>	persistent URL (to do)</li>
            </ul>
        </div> -->
        <div class="col-sm-8 col-sm-offset-2">
            {% if lastproblems %}
                <h3>Last Viability Problems</h3>
                <div id="row">
                    {% for problem in lastproblems %}
                        {% include 'sharekernel/viabilityproblem_card.html' %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <div class="col-sm-8 col-sm-offset-2">                       
            {% if lastkernels %}
                <h3>Last uploaded kernels</h3>
                <ul class="kernelslist">
                    {% for kernel in lastkernels %}
                    <li><a href="{% url 'sharekernel:visitresult' kernel.id %}" kernelid="{{kernel.id}}">{{kernel.parameters.viabilityproblem.title}} - {{kernel.author}} - {{kernel.submissiondate}}</a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

vinosite/sharekernel/templates/sharekernel/index.html
Could you check the information below : 

vinosite/sharekernel/templates/sharekernel/results_tree.html
{% extends "base.html" %}

{% load staticfiles %}
{% load sort_by %}

{% block body %}

{% load bootstrap3 %}
<div class="container" id="problem-picker">
    <div class="col-md-6">
            <label for="tab">Group by: </label>
            <div id="tab" class="btn-group" data-toggle="buttons">
				<a href="#tree-problem-view" class="btn btn-default active" data-toggle="tab">
					<input type="radio">Viability problems</a>
				<a href="#tree-software-view" class="btn btn-default" data-toggle="tab">
					<input type="radio">Softwares</a>
			</div>
        <div class="tab-content">
        <div class="tab-pane active" id="tree-problem-view">
            <ul>
                <li><span class="label label-default" title="Viability problem">VP</span>
                    <a class="btn btn-default btn-xs btn-new-problem" href="{% url 'sharekernel:newproblem' %}" role="button">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Describe a new viability problem
                    </a>
                </li>
                {% for problem in problems %}
                    <li><span class="label label-default" title="Viability problem">VP</span>
                        <a href="{% url 'sharekernel:visitviabilityproblem' problem.pk %}">{{ problem.pk }} - {{ problem.title }} ({{problem.statevariables.count}}-D)</a> :
                    <ul>
                        {% for param in problem.parameters_set.all %}
                            <li><span class="label label-default" title="Problem parameters">P</span>
                               {{ param.pk }} -  {{ param.dynamicsparametervalues }}
                            </li>
                            {% regroup param.results_set.all|sort_by:'software' by software as resultsbysoftware %}
                            <ul>
                            {% for resultbysoftware in resultsbysoftware %}
                                <li><span class="label label-default" title="Software">S</span> {{ resultbysoftware.grouper.title }} v.{{ resultbysoftware.grouper.version }}</li>
                                    <ul>
                                    {% for result in resultbysoftware.list %}
                                        <li><span class="label label-default" title="Viability results">R</span>
                                            <a href="{% url 'sharekernel:visitresult' result.pk %}">{{ result.title }} ({{ result.resultformat.title }})</a>
                                        </li>
                                    {% endfor %}
                                    <li><span class="label label-default" title="Viability results">R</span>
                                        <a class="btn btn-default btn-xs btn-new-results" href="{% url 'sharekernel:kerneluploadpage' param.pk resultbysoftware.grouper.id %}" role="button">
                                            <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Upload a result
                                        </a>
                                    </li>
                                    </ul>
                            {% endfor %}
                            <li><span class="label label-default" title="Problem parameters">P</span>
                                <a class="btn btn-default btn-xs btn-new-results" href="{% url 'sharekernel:newsoftware' %}" role="button">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a new software
                                </a>
                            </li>

                            </ul>
                        {% endfor %}
                        <li><span class="label label-default" title="Problem parameters">P</span>
                            <a class="btn btn-default btn-xs btn-new-parameters" href="{% url 'sharekernel:newparameters' problem.pk %}" role="button">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a new set of parameters
                            </a>
                        </li>
                    </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="tab-pane" id="tree-software-view">
            <ul>
                <li><span class="label label-default" title="Viability results">R</span>
                    <a class="btn btn-default btn-xs btn-new-results" href="{% url 'sharekernel:newsoftware' %}" role="button">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Describe a new software
                    </a>
                </li>
                {% for algo in softwares %}
                    <li><span class="label label-default" title="Software">S</span> {{ algo.title }} - v.{{ algo.version }} :
                    {% regroup algo.results_set.all|sort_by:'parameters' by parameters as resultsbyparam %}
                    {% regroup resultsbyparam by grouper.viabilityproblem as resultsbyvp %}
                    <ul>{% for resultbyvp in resultsbyvp %}
                        <li><span class="label label-default" title="Viability problem">VP</span>
                            <a href="{% url 'sharekernel:visitviabilityproblem' resultbyvp.grouper.pk %}">
                                {{ resultbyvp.grouper.pk }} - {{ resultbyvp.grouper.title }}  ({{resultbyvp.grouper.statevariables.count}}-D)
                            </a>
                        </li>
                        <ul>
                            {% for resultbyparam in resultsbyparam %}
                            {% ifequal resultbyparam.grouper.viabilityproblem.pk resultbyvp.grouper.pk %}
                                <li><span class="label label-default" title="Problem parameters">P</span>
                                    {{ resultbyparam.grouper.pk }} - {{ resultbyparam.grouper.dynamicsparametervalues }}
                                </li>
                                <ul>
                                    {% for result in resultbyparam.list %}
                                    <li><span class="label label-default" title="Viability results">R</span>
                                        <a href="{% url 'sharekernel:visitresult' result.pk %}">
                                            {{ result.title }} ({{ result.resultformat.title }})
                                        </a>
                                    </li>
                                    {% endfor %}
                                    <li><span class="label label-default" title="Viability results">R</span>
                                        <a class="btn btn-default btn-xs btn-new-results" href="{% url 'sharekernel:kerneluploadpage' resultbyparam.grouper.id algo.pk  %}" role="button">
                                            <span class="glyphicon glyphicon-upload" aria-hidden="true"></span> Upload a result
                                        </a>
                                    </li>

                                </ul>
                            {% endifequal %}
                            {% endfor %}
                            <li><span class="label label-default" title="Problem parameters">P</span>
                                <a class="btn btn-default btn-xs btn-new-parameters" href="{% url 'sharekernel:newparameters' resultbyvp.grouper.pk %}" role="button">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a new set of parameters
                                </a>
                            </li>
                        </ul>
                    {% endfor %}
                    <li><span class="label label-default" title="Viability problem">VP</span>
                        <a class="btn btn-default btn-xs btn-new-problem" href="{% url 'sharekernel:newproblem' %}" role="button">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add a new viability problem
                        </a>
                    </li>

                    </ul>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

<script>

  $('#groupByButton input').on('click', function () {
    console.log($(this));
    console.log($(this).attr('data-target'));
  });
</script>
{% endblock %}

vinosite/sharekernel/templates/sharekernel/visitsoftware.html
{% extends "base.html" %}

{% block body %}

<div class="container">
    <ol class="breadcrumb">
        <li><a href="{% url 'sharekernel:home' %}">Home</a></li>
    </ol>
{% if software.illustration %}
<img src="{{software.illustration.url}}" alt="{{software.title}}" width="460" height="345">
{% endif %}

        <h1>{{software.title}}
        </h1>
{% if version %} <h2>Version : {{software.version}} </h2>{% endif %}
        <div id="row">
            <div class="col-sm-12">
                        <p>This software was posted by {{software.submitter.id}} on {{software.submissiondate}}.</p>

                <div id="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <h4> This software was implemented by {{software.author}}. {% if software.publication %} It is described in 
                            <i>{{software.publication}}.</i>{% endif%} {% if software.website %}More information is available at {{software.website}}.{% endif %}
                           {% if software.contact %} Contact : {{software.contact}}.{% endif %}</h4>
                        <p>{% if softparval %}Beyond the viability problem definition,  running the software requires the specification of the following parameters :
                         <ul>{% for i in softparval%}<li> {{i}} </li>{% endfor %}
                         </ul>{% else %} The software parameters are not specified.{% endif %}</p>
                        <p>{% if software.description %} Description : {{software.description}}{% endif %}</p>

                    </div>
                </div>
            </div>
        </div>
</div>


{% endblock %}